### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by ashelleyPurdue** [ProPuke/electron-shared#2]
Trying to build this on a fresh Ubuntu VM, but the VM is missing some libraries that this project depends on.  Care to share a list of requirements in the readme, whenever you get around to it?

**Comment by ProPuke** [comment]
Hi @ashelleyPurdue, I've added in a brief build guide.
Does that make sense and build okay for you?

**Comment by ProPuke** [comment]
Whoops wait, forgot to mention the submodules...

**Comment by ashelleyPurdue** [comment]
Might want to mention that cmake is required, too.

**Comment by ashelleyPurdue** [comment]
Also, there's a mistake in the instructions for building for windows(on linux).  It references makefile.win32, but the file name is actually makefile.mingw32.

Also, I get the following error when running "make -f makefile.mingw32":

` make: i686-w64-mingw32-gcc: Command not found
makefile.mingw32:23: recipe for target 'obj/mingw32/main.o' failed
make: *** [obj/mingw32/main.o] Error 127 `

Is this actually meant to be built from Cygwin on a Windows machine, rather than on Linux?

**Comment by ProPuke** [comment]
Whoops, should have said `.mingw32` there, you're right:

It is meant to built from Linux, for Windows  
`i686-w64-mingw32-gcc` *should* be a part of `mingw-w64` (or is on debian). Do you have `mingw-w64` installed?

I'm hoping the executable doesn't have different names on different repos

**Comment by ashelleyPurdue** [comment]
I went ahead and installed mingw-w64 on my WSL Ubuntu on my PC at home.  It compiled just fine, but it doesn't run on WSL(though that may just be because WSL doesn't do GUI apps...)

On a related note, the latest windows exe does not work on my PC at home, despite doing fine on my work PC.

**Comment by ProPuke** [comment]
okay, sounds like it's building okay, but there's other probs
I'm gonna close this as complete, and hunt down the runtime issue
Cheers
