### ISSUE TITLE
Windows executable seemingly does nothing.

### ISSUE THREAD

**Issue by ashelleyPurdue** [ProPuke/electron-shared#3]
I tried it in multiple terminals.  In most of them, running electron-shared yields no output.  On Git Bash, however, it yields a seg fault.

Version: v0.1-alpha.3, electron-shared-win32-ia32.exe

To reproduce:

* copy tests/electron-quick-start to a separate folder named "app"(or just rename it if you're lazy)
* Place electron-shared-win32-ia32.exe in the folder beside "app".  Rename it to "electron-shared.exe" for convenience.
* Open git bash here, and type "./electron-shared".  You'll get a seg fault.
* Open cygwin here, and type "./electron-shared".  You'll get no output.
* Open cmd here, and type "electron-shared.exe".  You'll get no output.
* Open powershell here, and type "./electron-shared.exe".  You'll get no output.
* Double click the executable.  Still nothing.

**Comment by ProPuke** [comment]
Thanks again @ashelleyPurdue!

Alpha 4 should hopefully fix this for everyone and it should actually _work_, now!

**Comment by ashelleyPurdue** [comment]
Indeed it does!  Thanks!

**Comment by ashelleyPurdue** [comment]
Well, it works on my computer at work, but not on my computer at home apparently.  On my home computer, running electron-shared.exe from git bash still results in a segfault.

**Comment by ProPuke** [comment]
hmm.. If you launch it from cmd does it echo out any output before it dies?

**Comment by ashelleyPurdue** [comment]
Nope.  Not even "segfault".  In fact, it's behaving basically the same as the old version.

**Comment by ProPuke** [comment]
Still a memory issue for me to find, then. I'll get hunting..

**Comment by ashelleyPurdue** [comment]
I've narrowed it down to this bit of code right here:

```
#ifdef _WIN32
		if(AttachConsole(ATTACH_PARENT_PROCESS)||AttachConsole(GetCurrentProcessId())){
			freopen("CONIN$", "r", stdin);
			freopen("CONOUT$", "w", stdout);
			freopen("CONOUT$", "w", stderr);
		}

#endif
```

It's near the beginning of main.

**Comment by ProPuke** [comment]
Seems I somehow got git in a tangle (git gremlins?) and the master branch had become detached from the alpha.4 fixes. So basically, the master was stuck on alpha.3 -_-

I've rebased it so the fixes are back in again.

Did these probs only appear on a build from source? If so, pulling the latest changes and building again from source should hopefully fix them. My bad.

I suspect that bit of code you mention is actually a red herring. There was some heap corruption going on, and the thing with heap probs is they go away and move around when changing other code; So I suspect (hope) it was just the missing fixes from before.

Do let me know if they still occur though.

Thanks for all help and reports here

**Comment by ashelleyPurdue** [comment]
No problem.  I was experiencing these issues with both the git release *and* the one I built myself.  I'll give these changes a test run real quick.

**Comment by ashelleyPurdue** [comment]
Well, it finally compiled.  Nope, it still gives me a segfault even after pulling.

**Comment by ProPuke** [comment]
okay, cheers. I'll keep hunting.

**Comment by ashelleyPurdue** [comment]
Are you even able to reproduce it on your end?

**Comment by ProPuke** [comment]
nope. Fine for me :/
Maybe I should set up a crashdump workflow, or some tooling for finding possible memory probs.

**Comment by ashelleyPurdue** [comment]
The crash itself is occuring on line 930 of main.c.  If the problem is heap 
corruption, it would be because of something you did before that line. 
The code right above it looks like this:

```
int main(int argc, const char *argv[]) {
	char *projectPath = "app";
	bool projectPathSpecified = false;
	bool noDownload = false;
	bool downloadOnly = false;
	bool silent = false;

	char **electronParams = malloc((argc+1+1)*sizeof(const char*)); // +1 in case a project path wasn't included and we append one, +1 for end null
	int electronParamCount = 2; //we'll leave room for the electron path and the project path, which will be param 1

	#ifdef _WIN32
		if(AttachConsole(ATTACH_PARENT_PROCESS)||AttachConsole(GetCurrentProcessId())){
			freopen("CONIN$", "r", stdin);
			freopen("CONOUT$", "w", stdout);    // Segfault here
			freopen("CONOUT$", "w", stderr);
		}
	#endif
```

The only heap-related thing you've done so far was allocate memory for **electronParams.
Unless somehow there is code executing *before* main, that would be the only place
heap corruption could occur.  If that line is corrupting the heap, then replacing it with "NULL"
should cause the program to make it further before crashing.  I tried that, and
it still crashed in the exact same place.  So, that line is not the culprit.

My mental model is pretty thoroughly destroyed now.

**Comment by ashelleyPurdue** [comment]
Turns out the seg fault is actually occuring further down the line than that.  I was using printf instead of fprintf for locating it.

**Comment by ashelleyPurdue** [comment]
Is there anything I can do to help you reproduce this on your machine?  Any information that might be of use?

**Comment by ashelleyPurdue** [comment]
I've tried this on two other computers, and they both work without a hitch.  Since this issue can only be replicated on *one* specific computer, I'm going to go ahead and close this issue.
