### ISSUE TITLE
electron-shared fails when run through WSL Bash on Ubuntu

### ISSUE THREAD

**Issue by ashelleyPurdue** [ProPuke/electron-shared#4]
To reproduce:

* Open WSL Bash on Ubuntu on a Windows 10 machine
* Clone this repo and run "make" to build
* Copy or move the resulting "electron-shared" file to the "test" folder
* cd to the "test" folder and run "./electron-shared electron-quick-start"

You'll receive the following console output:
```./electron-shared electron-quick-start
This application requires Electron ^4.0.7
Unable to init server: Could not connect: Connection refused
Unable to initialise libui
  Cannot open display:
Fetching release list from GitHub...
Downloading Electron 4.1.0...
Extracting...
Launching Electron 4.1.0 (^4.0.7)...
/home/ashelley/.cache/electron-shared/4.1.0/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory```

**Comment by ProPuke** [comment]
This looks to just be a limitation of WSL not supporting gui apps (except for the final error about libnss3)

If you install X from WSL then execute `export DISPLAY=:0` before executing `./electron-shared` it should have gui access (or so the net tells me).

libnss3 looks to be a library electron needs (for managing keys, apparently), that wsl ubuntu doesn't have as standard.

Besides that, electron-shared actually seems to be running correctly. It's electron, afterwards, that reports the error. (well, electron-shared complains a little about no gui, but carries on anyway)

**Comment by ashelleyPurdue** [comment]
Closing this issue then, that was a brain fart on my part.
